// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v6.33.4
// source: export/library.proto

package export

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HTTP 请求
type HttpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method    string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                                                                           // HTTP方法: GET, POST, PUT, DELETE等
	Url       string            `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                                                                                                 // 完整的请求URL
	Headers   map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 请求头
	Body      []byte            `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                                                                               // 请求体
	TimeoutMs int64             `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`                                                                   // 超时时间(毫秒)，0表示使用默认超时
}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// HTTP 响应
type HttpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                                                        // 请求是否成功
	Error      string            `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                                                                             // 错误信息（如果失败）
	StatusCode int32             `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                // HTTP状态码
	Headers    map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 响应头
	Body       []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                                                                                               // 响应体
}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *HttpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HttpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// HTTP Library - 为 WASM 插件提供 HTTP 请求能力
// 由于 WASM 环境不支持 net/http 包，本 library 通过 host 函数代理实现 HTTP 请求
// go:plugin type=host module=http-library
type HttpLibrary interface {
	// 发起 HTTP 请求
	DoRequest(context.Context, *HttpRequest) (*HttpResponse, error)
}
