// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v6.33.4
// source: api/pbplugin/plugin.proto

package pbplugin

import (
	context "context"
	emptypb "github.com/knqyf263/go-plugin/types/known/emptypb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取插件信息响应
type GetPluginInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Info    *PluginInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetPluginInfoResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetPluginInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPluginInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPluginInfoResponse) GetInfo() *PluginInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 插件信息服务定义
type PluginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author      string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Homepage    string `protobuf:"bytes,5,opt,name=homepage,proto3" json:"homepage,omitempty"`
	EntryPath   string `protobuf:"bytes,6,opt,name=entry_path,json=entryPath,proto3" json:"entry_path,omitempty"` // 插件入口路径，如 "/xiaomi"
}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *PluginInfo) GetEntryPath() string {
	if x != nil {
		return x.EntryPath
	}
	return ""
}

type InitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId int64 `protobuf:"varint,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"` // 插件ID
}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *InitRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

// 定时器回调请求
type OnTimerCallbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId uint64 `protobuf:"varint,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"` // 定时器ID
}

func (x *OnTimerCallbackRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *OnTimerCallbackRequest) GetTimerId() uint64 {
	if x != nil {
		return x.TimerId
	}
	return 0
}

// 取消定时器请求
type CancelTimerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId  uint64 `protobuf:"varint,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`    // 定时器ID
	PluginId int64  `protobuf:"varint,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"` // 插件ID
}

func (x *CancelTimerRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CancelTimerRequest) GetTimerId() uint64 {
	if x != nil {
		return x.TimerId
	}
	return 0
}

func (x *CancelTimerRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

// 路由调用请求
type CallRouterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method      string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                                                                           // HTTP方法: GET, POST, PUT, DELETE等
	Path        string            `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                                                                               // 路由路径
	QueryString string            `protobuf:"bytes,3,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`                                                              // 查询字符串
	Headers     map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 请求头
	Body        []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                                                                                               // 请求体
}

func (x *CallRouterRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CallRouterRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRouterRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CallRouterRequest) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

func (x *CallRouterRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallRouterRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// 路由调用响应
type CallRouterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message    string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode int32             `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                // HTTP状态码
	Headers    map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 响应头
	Body       []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                                                                                               // 响应体
}

func (x *CallRouterResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CallRouterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CallRouterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CallRouterResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CallRouterResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallRouterResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// 注册延时任务请求
type RegisterDelayTimerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId           uint64 `protobuf:"varint,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`                               // 定时器ID
	DelayMilliseconds int64  `protobuf:"varint,2,opt,name=delay_milliseconds,json=delayMilliseconds,proto3" json:"delay_milliseconds,omitempty"` // 延迟毫秒
	PluginId          int64  `protobuf:"varint,3,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`                            // 插件ID
}

func (x *RegisterDelayTimerRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RegisterDelayTimerRequest) GetTimerId() uint64 {
	if x != nil {
		return x.TimerId
	}
	return 0
}

func (x *RegisterDelayTimerRequest) GetDelayMilliseconds() int64 {
	if x != nil {
		return x.DelayMilliseconds
	}
	return 0
}

func (x *RegisterDelayTimerRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

// 注册路由请求
type RegisterRouterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method        string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                       // HTTP 方法：GET, POST, PUT, DELETE 等
	Pattern       string `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`                                     // 路由模式
	HandlerFuncId uint64 `protobuf:"varint,3,opt,name=handler_func_id,json=handlerFuncId,proto3" json:"handler_func_id,omitempty"` // 处理函数 ID
	PluginId      int64  `protobuf:"varint,4,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`                  // 插件 ID
	RequiresAuth  bool   `protobuf:"varint,5,opt,name=requires_auth,json=requiresAuth,proto3" json:"requires_auth,omitempty"`      // 是否需要认证
}

func (x *RegisterRouterRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RegisterRouterRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RegisterRouterRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *RegisterRouterRequest) GetHandlerFuncId() uint64 {
	if x != nil {
		return x.HandlerFuncId
	}
	return 0
}

func (x *RegisterRouterRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

func (x *RegisterRouterRequest) GetRequiresAuth() bool {
	if x != nil {
		return x.RequiresAuth
	}
	return false
}

// 路由回调请求
type OnRouterCallbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerFuncId uint64 `protobuf:"varint,1,opt,name=handler_func_id,json=handlerFuncId,proto3" json:"handler_func_id,omitempty"` // 处理函数ID
	// HTTP请求参数将会通过字节流传输
	RequestData []byte `protobuf:"bytes,2,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"` // 序列化的HTTP请求数据
}

func (x *OnRouterCallbackRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *OnRouterCallbackRequest) GetHandlerFuncId() uint64 {
	if x != nil {
		return x.HandlerFuncId
	}
	return 0
}

func (x *OnRouterCallbackRequest) GetRequestData() []byte {
	if x != nil {
		return x.RequestData
	}
	return nil
}

// 路由回调响应
type OnRouterCallbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message    string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode int32             `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                // HTTP 状态码
	Headers    map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 响应头
	Body       []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                                                                                               // 响应体
}

func (x *OnRouterCallbackResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *OnRouterCallbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OnRouterCallbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OnRouterCallbackResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *OnRouterCallbackResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *OnRouterCallbackResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// 获取插件 JWT Token 响应
type GetPluginJWTTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetPluginJWTTokenResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetPluginJWTTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPluginJWTTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPluginJWTTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 插件服务定义
// go:plugin type=plugin version=4
type PluginService interface {
	// 获取插件信息
	GetPluginInfo(context.Context, *emptypb.Empty) (*GetPluginInfoResponse, error)
	// 初始化插件
	Init(context.Context, *InitRequest) (*emptypb.Empty, error)
	// 反初始化插件
	Deinit(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// 定时器回调
	OnTimerCallback(context.Context, *OnTimerCallbackRequest) (*emptypb.Empty, error)
	// 路由回调
	OnRouterCallback(context.Context, *OnRouterCallbackRequest) (*OnRouterCallbackResponse, error)
}

// 主程序服务定义
// go:plugin type=host
type HostFunctions interface {
	// 路由调用
	CallRouter(context.Context, *CallRouterRequest) (*CallRouterResponse, error)
	// 注册延时任务
	RegisterDelayTimer(context.Context, *RegisterDelayTimerRequest) (*emptypb.Empty, error)
	// 取消延时任务
	CancelDelayTimer(context.Context, *CancelTimerRequest) (*emptypb.Empty, error)
	// 注册路由
	RegisterRouter(context.Context, *RegisterRouterRequest) (*emptypb.Empty, error)
	// 获取插件 JWT Token
	GetPluginJWTToken(context.Context, *emptypb.Empty) (*GetPluginJWTTokenResponse, error)
}
