// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.12
// source: api/pbplugin/plugin.proto

package pbplugin

import (
	context "context"
	emptypb "github.com/knqyf263/go-plugin/types/known/emptypb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取插件信息响应
type GetPluginInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Info    *PluginInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetPluginInfoResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetPluginInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPluginInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPluginInfoResponse) GetInfo() *PluginInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 插件信息服务定义
type PluginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author      string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Homepage    string `protobuf:"bytes,5,opt,name=homepage,proto3" json:"homepage,omitempty"`
	EntryPath   string `protobuf:"bytes,6,opt,name=entry_path,json=entryPath,proto3" json:"entry_path,omitempty"` // 插件入口路径，如 "/xiaomi"
}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *PluginInfo) GetEntryPath() string {
	if x != nil {
		return x.EntryPath
	}
	return ""
}

type InitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId int64 `protobuf:"varint,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"` // 插件ID
}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *InitRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

// 定时器回调请求
type OnTimerCallbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId uint64 `protobuf:"varint,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"` // 定时器ID
}

func (x *OnTimerCallbackRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *OnTimerCallbackRequest) GetTimerId() uint64 {
	if x != nil {
		return x.TimerId
	}
	return 0
}

// 取消定时器请求
type CancelTimerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId  uint64 `protobuf:"varint,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`    // 定时器ID
	PluginId int64  `protobuf:"varint,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"` // 插件ID
}

func (x *CancelTimerRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CancelTimerRequest) GetTimerId() uint64 {
	if x != nil {
		return x.TimerId
	}
	return 0
}

func (x *CancelTimerRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

// 路由调用请求
type CallRouterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method      string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                                                                           // HTTP方法: GET, POST, PUT, DELETE等
	Path        string            `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                                                                               // 路由路径
	QueryString string            `protobuf:"bytes,3,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`                                                              // 查询字符串
	Headers     map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 请求头
	Body        []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                                                                                               // 请求体
}

func (x *CallRouterRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CallRouterRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRouterRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CallRouterRequest) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

func (x *CallRouterRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallRouterRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// 路由调用响应
type CallRouterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message    string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode int32             `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                // HTTP状态码
	Headers    map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 响应头
	Body       []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                                                                                               // 响应体
}

func (x *CallRouterResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CallRouterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CallRouterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CallRouterResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CallRouterResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallRouterResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// 注册延时任务请求
type RegisterDelayTimerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId           uint64 `protobuf:"varint,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`                               // 定时器ID
	DelayMilliseconds int64  `protobuf:"varint,2,opt,name=delay_milliseconds,json=delayMilliseconds,proto3" json:"delay_milliseconds,omitempty"` // 延迟毫秒
	PluginId          int64  `protobuf:"varint,3,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`                            // 插件ID
}

func (x *RegisterDelayTimerRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RegisterDelayTimerRequest) GetTimerId() uint64 {
	if x != nil {
		return x.TimerId
	}
	return 0
}

func (x *RegisterDelayTimerRequest) GetDelayMilliseconds() int64 {
	if x != nil {
		return x.DelayMilliseconds
	}
	return 0
}

func (x *RegisterDelayTimerRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

// 注册路由请求
type RegisterRouterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method        string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                       // HTTP 方法：GET, POST, PUT, DELETE 等
	Pattern       string `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`                                     // 路由模式
	HandlerFuncId uint64 `protobuf:"varint,3,opt,name=handler_func_id,json=handlerFuncId,proto3" json:"handler_func_id,omitempty"` // 处理函数 ID
	PluginId      int64  `protobuf:"varint,4,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`                  // 插件 ID
	RequiresAuth  bool   `protobuf:"varint,5,opt,name=requires_auth,json=requiresAuth,proto3" json:"requires_auth,omitempty"`      // 是否需要认证
}

func (x *RegisterRouterRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RegisterRouterRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RegisterRouterRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *RegisterRouterRequest) GetHandlerFuncId() uint64 {
	if x != nil {
		return x.HandlerFuncId
	}
	return 0
}

func (x *RegisterRouterRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

func (x *RegisterRouterRequest) GetRequiresAuth() bool {
	if x != nil {
		return x.RequiresAuth
	}
	return false
}

// 路由回调请求
type OnRouterCallbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerFuncId uint64 `protobuf:"varint,1,opt,name=handler_func_id,json=handlerFuncId,proto3" json:"handler_func_id,omitempty"` // 处理函数ID
	// HTTP请求参数将会通过字节流传输
	RequestData []byte `protobuf:"bytes,2,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"` // 序列化的HTTP请求数据
}

func (x *OnRouterCallbackRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *OnRouterCallbackRequest) GetHandlerFuncId() uint64 {
	if x != nil {
		return x.HandlerFuncId
	}
	return 0
}

func (x *OnRouterCallbackRequest) GetRequestData() []byte {
	if x != nil {
		return x.RequestData
	}
	return nil
}

// 路由回调响应
type OnRouterCallbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success    bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message    string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode int32             `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`                                                                // HTTP 状态码
	Headers    map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 响应头
	Body       []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`                                                                                               // 响应体
}

func (x *OnRouterCallbackResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *OnRouterCallbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OnRouterCallbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OnRouterCallbackResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *OnRouterCallbackResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *OnRouterCallbackResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// 获取插件 JWT Token 响应
type GetPluginJWTTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetPluginJWTTokenResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetPluginJWTTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPluginJWTTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPluginJWTTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 创建 JS 运行时环境请求
type CreateJSEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvId    string `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`           // 环境 ID
	InitCode string `protobuf:"bytes,2,opt,name=init_code,json=initCode,proto3" json:"init_code,omitempty"`  // 初始化代码
	PluginId int64  `protobuf:"varint,3,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"` // 插件 ID
}

func (x *CreateJSEnvRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CreateJSEnvRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *CreateJSEnvRequest) GetInitCode() string {
	if x != nil {
		return x.InitCode
	}
	return ""
}

func (x *CreateJSEnvRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

// 创建 JS 运行时环境响应
type CreateJSEnvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateJSEnvResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CreateJSEnvResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateJSEnvResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 执行 JS 代码请求
type ExecuteJSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvId          string   `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`                              // 环境 ID
	Code           string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                             // JS 代码
	TimeoutMs      int64    `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`                 // 超时毫秒数
	PluginId       int64    `protobuf:"varint,4,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`                    // 插件 ID
	WaitEventNames []string `protobuf:"bytes,5,rep,name=wait_event_names,json=waitEventNames,proto3" json:"wait_event_names,omitempty"` // 需要等待的事件名称列表（如 "dispatchResult", "dispatchError"）
}

func (x *ExecuteJSRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExecuteJSRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *ExecuteJSRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteJSRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecuteJSRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

func (x *ExecuteJSRequest) GetWaitEventNames() []string {
	if x != nil {
		return x.WaitEventNames
	}
	return nil
}

// 执行 JS 代码响应
type ExecuteJSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result  string     `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // 执行结果（JSON 字符串）
	Events  []*JSEvent `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"` // 执行期间收集的事件
}

func (x *ExecuteJSResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExecuteJSResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteJSResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteJSResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecuteJSResponse) GetEvents() []*JSEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// JS 事件
type JSEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvId string `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data  string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON 字符串
}

func (x *JSEvent) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *JSEvent) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *JSEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JSEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// 销毁 JS 运行时环境请求
type DestroyJSEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvId    string `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`           // 环境 ID
	PluginId int64  `protobuf:"varint,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"` // 插件 ID
}

func (x *DestroyJSEnvRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DestroyJSEnvRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *DestroyJSEnvRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

// 销毁 JS 运行时环境响应
type DestroyJSEnvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DestroyJSEnvResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DestroyJSEnvResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DestroyJSEnvResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 并行执行多个 JS 环境的请求（竞速模式，返回第一个成功结果）
type ExecuteJSParallelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Calls         []*ExecuteJSRequest `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`                                       // 待执行的 JS 调用列表
	MaxConcurrent int32               `protobuf:"varint,2,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"` // 最大并发数（0 = 全部并行）
}

func (x *ExecuteJSParallelRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExecuteJSParallelRequest) GetCalls() []*ExecuteJSRequest {
	if x != nil {
		return x.Calls
	}
	return nil
}

func (x *ExecuteJSParallelRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

// 并行执行响应
type ExecuteJSParallelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool               `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否有至少一个调用成功
	Message      string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SuccessIndex int32              `protobuf:"varint,3,opt,name=success_index,json=successIndex,proto3" json:"success_index,omitempty"` // 成功的调用索引（-1 表示全部失败）
	Result       *ExecuteJSResponse `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`                                  // 成功的调用结果
	Errors       []string           `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`                                  // 各调用的错误信息（成功的为空字符串）
}

func (x *ExecuteJSParallelResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExecuteJSParallelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteJSParallelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteJSParallelResponse) GetSuccessIndex() int32 {
	if x != nil {
		return x.SuccessIndex
	}
	return 0
}

func (x *ExecuteJSParallelResponse) GetResult() *ExecuteJSResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteJSParallelResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// 执行外部命令请求
type ExecuteCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command    string            `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`                                                                                 // 可执行文件名（如 "cloudflared"，不含路径）
	Args       []string          `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`                                                                                       // 命令参数列表
	Env        map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 额外环境变量
	PluginId   int64             `protobuf:"varint,4,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`                                                              // 插件 ID
	Background bool              `protobuf:"varint,5,opt,name=background,proto3" json:"background,omitempty"`                                                                          // 是否后台运行
	ProcessId  string            `protobuf:"bytes,6,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`                                                            // 进程标识符（后台模式必填）
}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExecuteCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteCommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteCommandRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

func (x *ExecuteCommandRequest) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

func (x *ExecuteCommandRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

// 执行外部命令响应
type ExecuteCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stdout    string `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr    string `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode  int32  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ProcessId string `protobuf:"bytes,6,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExecuteCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteCommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteCommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteCommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteCommandResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

// 停止后台命令请求
type StopCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	PluginId  int64  `protobuf:"varint,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
}

func (x *StopCommandRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *StopCommandRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *StopCommandRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

// 停止后台命令响应
type StopCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StopCommandResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *StopCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopCommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取后台命令输出请求
type GetCommandOutputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	PluginId  int64  `protobuf:"varint,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
}

func (x *GetCommandOutputRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetCommandOutputRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *GetCommandOutputRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

// 获取后台命令输出响应
type GetCommandOutputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stdout   string `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr   string `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Running  bool   `protobuf:"varint,5,opt,name=running,proto3" json:"running,omitempty"`
	ExitCode int32  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
}

func (x *GetCommandOutputResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetCommandOutputResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCommandOutputResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCommandOutputResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *GetCommandOutputResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *GetCommandOutputResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *GetCommandOutputResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// 异步下载文件请求
type DownloadFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url               string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                                                        // 下载 URL
	DestPath          string `protobuf:"bytes,2,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"`                              // 目标路径（WASM 视角，如 "/cloudflared/bin/cloudflared"）
	TaskId            string `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                    // 任务标识符（插件自定义，如 "download-cloudflared"）
	PluginId          int64  `protobuf:"varint,4,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`                             // 插件 ID
	ExtractTgz        bool   `protobuf:"varint,5,opt,name=extract_tgz,json=extractTgz,proto3" json:"extract_tgz,omitempty"`                       // 是否需要解压 .tgz（macOS 场景）
	ExtractTargetName string `protobuf:"bytes,6,opt,name=extract_target_name,json=extractTargetName,proto3" json:"extract_target_name,omitempty"` // 解压后目标文件名（如 "cloudflared"）
}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DownloadFileRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadFileRequest) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

func (x *DownloadFileRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DownloadFileRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

func (x *DownloadFileRequest) GetExtractTgz() bool {
	if x != nil {
		return x.ExtractTgz
	}
	return false
}

func (x *DownloadFileRequest) GetExtractTargetName() string {
	if x != nil {
		return x.ExtractTargetName
	}
	return ""
}

// 异步下载文件响应
type DownloadFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TaskId  string `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DownloadFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DownloadFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DownloadFileResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 获取下载任务状态请求
type GetDownloadStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`        // 任务标识符
	PluginId int64  `protobuf:"varint,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"` // 插件 ID
}

func (x *GetDownloadStatusRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetDownloadStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetDownloadStatusRequest) GetPluginId() int64 {
	if x != nil {
		return x.PluginId
	}
	return 0
}

// 获取下载任务状态响应
type GetDownloadStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success         bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status          string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                           // "downloading", "completed", "failed", "not_found"
	DownloadedBytes int64  `protobuf:"varint,4,opt,name=downloaded_bytes,json=downloadedBytes,proto3" json:"downloaded_bytes,omitempty"` // 已下载字节数
	TotalBytes      int64  `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`                // 文件总字节数（-1 表示未知）
	ProgressPercent int32  `protobuf:"varint,6,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"` // 下载进度百分比 0-100
	Error           string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`                                             // 失败时的错误信息
}

func (x *GetDownloadStatusResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetDownloadStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetDownloadStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetDownloadStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDownloadStatusResponse) GetDownloadedBytes() int64 {
	if x != nil {
		return x.DownloadedBytes
	}
	return 0
}

func (x *GetDownloadStatusResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *GetDownloadStatusResponse) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *GetDownloadStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 插件服务定义
// go:plugin type=plugin version=4
type PluginService interface {
	// 获取插件信息
	GetPluginInfo(context.Context, *emptypb.Empty) (*GetPluginInfoResponse, error)
	// 初始化插件
	Init(context.Context, *InitRequest) (*emptypb.Empty, error)
	// 反初始化插件
	Deinit(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// 定时器回调
	OnTimerCallback(context.Context, *OnTimerCallbackRequest) (*emptypb.Empty, error)
	// 路由回调
	OnRouterCallback(context.Context, *OnRouterCallbackRequest) (*OnRouterCallbackResponse, error)
}

// 主程序服务定义
// go:plugin type=host
type HostFunctions interface {
	// 路由调用
	CallRouter(context.Context, *CallRouterRequest) (*CallRouterResponse, error)
	// 注册延时任务
	RegisterDelayTimer(context.Context, *RegisterDelayTimerRequest) (*emptypb.Empty, error)
	// 取消延时任务
	CancelDelayTimer(context.Context, *CancelTimerRequest) (*emptypb.Empty, error)
	// 注册路由
	RegisterRouter(context.Context, *RegisterRouterRequest) (*emptypb.Empty, error)
	// 获取插件 JWT Token
	GetPluginJWTToken(context.Context, *emptypb.Empty) (*GetPluginJWTTokenResponse, error)
	// JS 运行时管理（cqjs）
	CreateJSEnv(context.Context, *CreateJSEnvRequest) (*CreateJSEnvResponse, error)
	ExecuteJS(context.Context, *ExecuteJSRequest) (*ExecuteJSResponse, error)
	DestroyJSEnv(context.Context, *DestroyJSEnvRequest) (*DestroyJSEnvResponse, error)
	// 并行执行多个 JS 环境的代码（竞速模式）
	ExecuteJSParallel(context.Context, *ExecuteJSParallelRequest) (*ExecuteJSParallelResponse, error)
	// 执行外部命令（受双重白名单限制）
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	// 停止后台命令
	StopCommand(context.Context, *StopCommandRequest) (*StopCommandResponse, error)
	// 获取后台命令输出
	GetCommandOutput(context.Context, *GetCommandOutputRequest) (*GetCommandOutputResponse, error)
	// 异步下载文件到插件数据目录
	DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileResponse, error)
	// 获取下载任务状态
	GetDownloadStatus(context.Context, *GetDownloadStatusRequest) (*GetDownloadStatusResponse, error)
}
